version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php_trader
    container_name: php_trader
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - .:/var/www
    ports:
      - 9001:9000
    command: composer install
